// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbjssmdqdzbrivraosiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRianNzbWRxZHpicml2cmFvc2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTUwNTgsImV4cCI6MjA2NDU5MTA1OH0.1qiloBwn4ibZ395SRfnl5SkFMLtF3mdIJ7CBymVD_wU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);